### ISSUE TITLE
Крашится sublime

### ISSUE THREAD

**Issue by belimposition** [Nitive/sublime-stylint-sorting#1]
Если в сортируемых стилях, в их значениях встречаются миксины, саблайм зависает
возможно не все миксины и\или не только, но вот при такой записи стабильно

```
        position relative
        width $(621px)
        height $(731px)
        background-image url('/assets/images/mobile/mob-thanks-bg.png')
        background-repeat no-repeat
        background-position 50% 0%
        background-size cover
        padding-top $(208px)
        padding-left $(82px)
        padding-right $(82px)
```

**Comment by Nitive** [comment]
Спасибо за фидбек.
Не получается воспроизвести ни на втором саблайме, ни на третьем.
Какая версия используется?
Что в консоли? (Открыть консоль View > Show Console)

**Comment by belimposition** [comment]
Попробовал воспроизвести - тоже не получилось, возможно причина была в другом
